version: '3.4'

volumes:
    app_data:

networks:
    exam:
        driver: bridge

services:
  backend-library-app:
    container_name: backend-library-app
    image: ${DOCKER_REGISTRY-}backendlibraryapp
    build:
      context: .
      dockerfile: backend-library-app/Dockerfile
    ports:
        - "8080:8080"
        - "8081:8081"
    environment:
        - ConnectionStrings__DefaultConnection=User ID=postgres; Password=postgres;Server=postgresdb;Port=5432;Database=LibraryDB; IntegratedSecurity=true;Pooling=true;
        - ASPNETCORE_URLS=http://+:8080
    networks:
        - exam
  
        
  postgres:
    image: postgres:latest
    build:
      context: ./resources/postgres
      dockerfile: Dockerfile
    container_name: postgresdb
    restart: always
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=LibraryDB
    ports:
        - "5432:5432"
    networks:
        - exam
    volumes:
        - app_data:/var/lib/postgresql/data

  samba:
    image: dperson/samba
    container_name: samba-container
    environment:
      - SAMBA_USER=admin
      - SAMBA_PASSWORD=password1
    ports:
      - "1445:445"
    volumes:
      - "app_data:/mount"
    command: -p -u "user;1234"
    stdin_open: true
    tty: true
    restart: always
    networks:
      - exam  